const ACCENT_CREAM = '#f3ebd2'
const MUTED_TEXT = '#b8b1a1'
const PRIMARY_BACKGROUND = '#0b0b0f'
const ACCENT_RED = '#8b1e2d'
const ACCENT_ORANGE = '#fdba74'
const ACCENT_PINK = '#f87171'
const ACCENT_DARK = '#2a2a33'
const SECONDARY_BACKGROUND = '#15151b'

export { ACCENT_CREAM, MUTED_TEXT, PRIMARY_BACKGROUND, ACCENT_RED, ACCENT_ORANGE, ACCENT_PINK, ACCENT_DARK, SECONDARY_BACKGROUND }